FROM maven:latest AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn -X -e package

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=/tmp/target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","mortgageCalculator.MortgageCalculatorController"]
